### ISSUE TITLE
Adding an option to choose TCP or UDP transport

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Noxwizard/dnscrypt-winclient#25]
I found [DNSCrypt Windows Service Manager](http://simonclausen.dk/projects/dnscrypt-winservicemgr/) and Simple DNSCrypt have implemented an option to choose TCP/UDP transport, but I have never seen which option in your client is available for it. So please adding this option.

**Comment by Noxwizard** [comment]
I previously supported this, but had to remove it as the CSV provided by [dnscrypt.org](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv) no longer provides that information, so it is not reliable to assume that any of those resolvers provides anything other than TCP.

**Comment by KrasnayaPloshchad** [comment]
On 28 Jul 2016 they allowed to query over TCP or UDP in their [specification](https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt), so you should follow it.

**Comment by Noxwizard** [comment]
TCP and UDP options have been supported since the very beginning by DNSCrypt. As I said before, my application used to support it as well. The problem still remains that the CSV does not provide this information, so the end user would have to guess as to whether a server supported UDP and on what ports. Until that information is once again provided in the CSV, this feature will not come back.
